stockanalysisdev/stock-analysis

- components/Actions/ActionsTable.tsx
- components/Chart/StockChart.tsx
- components/Controls/Export/Download.tsx
- components/Controls/Export/Restricted.tsx
- components/Controls/_Controls.tsx
- components/IPOs/RecentTable.tsx
- components/PriceChart/PriceChartChart.tsx
- next.config.js
- styles/globals.css
> IPO pages: Sort by IPO date was not working
> Stock Charts: Made volume bar colors transparent to reduce overlap
> Redirect /wp-login.php to its parent to get rid of error notices
> Fix x-axis ticks on some overview charts
> Make body background white
> Multiple minor bug fixes

- components/Actions/ActionsTable.tsx
- components/Controls/Export.tsx
- components/Controls/Export/Download.tsx
- components/Controls/Export/ExportItem.tsx
- components/Controls/_Controls.tsx
- components/Holdings/HoldingsPaywall.tsx
- components/Holdings/HoldingsTable.module.css
- components/Holdings/_HoldingsTable.tsx
- components/Layout/Sidebar/Newsletter.tsx
- functions/callBackEnd.ts
- pages/etf/[symbol]/holdings.tsx
- pages/pro/index.tsx
> Also added newsletter widget to holdings pages
>>> Reduced the font size a bit to fit the design better
> Make holdings load full data via ID instead of symbol
> Remove contact form link from /pro/
> Enabled table controls on Holdings pages (export, filter)

- components/Controls/Export/Restricted.tsx
- components/IPOs/CalendarTable.tsx
- pages/index.tsx
- pages/ipos/index.tsx
- Bug fix: IPO header for this week was missing
- Updated some meta descriptions
- Added cursor-pointer: hover to restricted export buttons
> Fix IPO header bug, update meta descriptions

- components/IPOs/CalendarStats.tsx
- components/IPOs/CalendarTable.tsx
- components/IPOs/CalendarTableMin.tsx
- components/IPOs/RecentTable.tsx
- components/IPOs/RecentTableMin.tsx
- components/Icons/Calendar.tsx
- pages/ipos/[year].tsx
- pages/ipos/calendar.tsx
- pages/ipos/index.tsx
- pages/ipos/news.tsx
- pages/ipos/statistics.tsx
- types/IpoRecent.ts
- types/IpoUpcoming.ts
- types/Ipos.ts
- Also cleaned up the type files for IPOs
> Add statistics widget to IPO calendar page

- components/Actions/ActionsTable.tsx
- components/Controls/SplitsFilter.tsx
- components/Controls/_Controls.tsx
- components/Tables/SymbolTable.tsx
- Also changed filterable tables so that they show the matched count instead of the full count
> Add option to filter stock splits by forward & reverse

- components/Actions/ActionsTable.module.css
- components/Actions/ActionsTable.tsx
- pages/stocks/[symbol]/chart.tsx
- pages/stocks/[symbol]/company.tsx
- pages/stocks/[symbol]/financials/balance-sheet.tsx
- pages/stocks/[symbol]/financials/cash-flow-statement.tsx
- pages/stocks/[symbol]/financials/index.tsx
- pages/stocks/[symbol]/financials/ratios.tsx
- pages/stocks/[symbol]/index.tsx
- pages/stocks/[symbol]/statistics.tsx
- Also fix a display bug on the corpoarate actions - spinoffs.
> Make stock page titles show full company name instead of shortened version

- components/Controls/Export/Restricted.tsx
- components/FinancialTable/_FinancialTable.tsx
- components/StockHeading/StockPrice.tsx
- components/StockScreener/_Results/ResultsBody/ResultsTable.tsx
- Add a loading indicator to screener.
- Add cursor pointer to restricted export items.
- Fix js errors and hide ratios on new IPOs.
> A few minor changes, bug fixes

- components/PriceChart/PriceChart.functions.tsx
- components/PriceChart/_PriceChart.tsx
- components/Unavailable.tsx
- If no data, show an "unavailable" message.
- Add support for stocks that have an alternative chart data source set
> Overview chart improvements

- components/IPOs/IPOSources.tsx
- components/Overview/TopTables.tsx
- Add a dedicated "Trending Stocks" page
- Added link to IPO API under Calendar
- Center all ads
- Fixed n/a values on upcoming IPO quotes
> Dedicated trending page

- components/Layout/LayoutSidebar.tsx
- pages/ipos/[year].tsx
- pages/ipos/calendar.tsx
- pages/ipos/filings.tsx
- pages/ipos/index.tsx
- pages/ipos/news.tsx
- pages/ipos/statistics.tsx
- pages/ipos/withdrawn.tsx
- pages/news/all-stocks.tsx
- pages/news/index.tsx
- pages/news/press-releases.tsx
- pages/trending/index.tsx
- styles/globals.css
- tailwind.config.js
Make side menu visible on 1280px
> Left menu on 1280px

- components/Icons/NavArrow.tsx
- components/Layout/Navigation/MainNav.tsx
- components/Layout/Navigation/NavItems/Menu.tsx
- components/Layout/Navigation/NavItems/NavItems.types.ts
- components/Layout/Navigation/NavItems/Single.tsx
- functions/helpers/matchPath.ts
- next-env.d.ts
- state/navMenuState.ts
- state/navState.ts
- styles/layout/sidenav.css
- Add dropdown functionality to the navigation menu
- IPOs and Screener now have a submenu
> Navigation dropdown functionality

- components/Layout/FocusedLayout.tsx
- components/Layout/Footer/_Footer.tsx
- components/Layout/Header/HeaderLogin.tsx
- components/Layout/UserLayout.tsx
- components/Layout/_Layout.tsx
- hooks/useAuth.ts
- package-lock.json
- package.json
- pages/contact.tsx
- pages/login.tsx
- pages/pro/my-account.tsx
- styles/layout/layout.css
- Put left nav back on my account page, login page, confirmation page and contact page
- Hide My Account link on My Account page
- Make footer always show on the bottom of the page via (min-h-screen, flex flex-col, flex-grow)
- Update supabase-js package to the latest version
> Layout improvements

- README.md
- example.env
- simplified setup instructions language
- add instruction to setup supabase
- created **example.env** to be used to populate **.env** file
@kristjanmar Please review 🙂
#233
> Update readme add supabase info

- components/Overview/NewsArea.tsx
- functions/apis/API.ts
> Abort Controller for NewsArea Added

- components/FinancialTable/HoverChart.tsx
- components/Forecasts/Estimates/EstimatesHoverChart.tsx
- components/Forecasts/Estimates/EstimatesTable.module.css
- components/Forecasts/Estimates/EstimatesTable.tsx
- components/Forecasts/Estimates/TableRow.tsx
- functions/tables/formatTableCell.tsx
- types/Forecast.ts
Forecasts: Add hover charts to the financial estimates table on the forecast pages
> Forecasts: Add estimate hover charts

- components/Layout/StockListLayout.tsx
- components/Markets/PageContext.tsx
- components/StockTable/Controls/TableTimestamp.tsx
- components/StockTable/Controls/TableTitle.tsx
- components/StockTable/TableContext.tsx
- components/StockTable/TableTypes.ts
- content/sitemap.mdx
- data/StockLists.tsx
- pages/list/[slug].tsx
- pages/list/index.tsx
- pages/markets/active.tsx
- pages/markets/gainers/[range].tsx
- pages/markets/gainers/index.tsx
- pages/markets/losers/[range].tsx
- pages/markets/losers/index.tsx
- pages/markets/premarket/gainers.tsx
- pages/markets/premarket/losers.tsx
- pages/sitemap.xml.tsx
- pages/stocks/index.tsx
- types/PageConfig.ts
- Use the select endpoint and stocktable to create lists of stock that are filtered and sorted by certain characteristics
- Change home page revalidation method to auto, there were some problems with manual revalidation on the home page
> New Feature: Stock Lists

- components/Ads/AdSense/ContentWide2.tsx
- components/Forecasts/Estimates/EstimateChart.tsx
- components/Forecasts/Estimates/EstimateChartArea.tsx
- components/Forecasts/Estimates/EstimatesTable.module.css
- components/Forecasts/PriceTarget/PriceTargetChart.tsx
- components/Forecasts/PriceTarget/_PriceTarget.tsx
- components/Forecasts/PriceTarget/target.functions.ts
- pages/stocks/[symbol]/forecast.tsx
- types/Forecast.ts
- Forecast pages: Add charts with revenue, EPS, revenue growth and EPS growth estimates.
> Estimate chart

- components/Forecasts/Estimates/EstimateChartArea.tsx
- components/Forecasts/Estimates/EstimateGrowthChart.tsx
- components/Forecasts/PriceTarget/PriceTargetChart.tsx
- package-lock.json
- package.json
> Forecast pages: Change estimates growth charts to bar charts

- components/StockLists/StockListStats.tsx
- pages/list/[slug].tsx
- At the top of the page, show total companies, total market cap and total revenue
> Add stats widgets to stock lists pages

- components/ErrorBoundary/ErrorBoundary.tsx
- components/ErrorBoundary/ErrorFallback.tsx
- components/Forecasts/Estimates/EstimatesTable.tsx
- hooks/useEvent.ts
- pages/_app.tsx
Add error boundary to log and debug uncaught client-side errors
> Error boundary

- components/Ads/AdSense/HeaderAd.tsx
- components/Pro/UpgradePrompt.tsx
- components/StockHeading/_StockHeading.tsx
> If logged in but not pro, show upgrade prompt instead of header ad

- auth/supabase/getUserInfo.ts
- auth/useAuth.ts
- components/Ads/AdSense/HeaderAd.tsx
- components/Loading/Spinner.tsx
- components/Pro/CancelSubscription.tsx
- components/Pro/MyAccount/GetSupport.tsx
- components/Pro/MyAccount/Reactivate.tsx
- components/Pro/MyAccount/_MyAccount.tsx
- pages/pro/cancel.tsx
- pages/pro/my-account.tsx
Also fine-tuned reactivation flow for inactive accounts
> Auth: Reorganized code for My Account page and improved UX
